[JOB]
task               = Optdensity

[PATH]
pp                 = ../../../DATA/
cell               = ../../../DATA/

[PP]
;O                  = o_pbe_v1.2.uspp.F.UPF 
;H                  = h_pbe_v1.4.uspp.F.UPF 
O                  = O.pbe-rrkjus.UPF
H                  = H.pbe-rrkjus.UPF

[OPT]
maxiter            = 500
econv              = 1e-5
olevel = 2


[GSYSTEM]
cell-file          = water_subcell.xyz
grid-ecut          = 2700
;grid-nr = 100 100 100
exc-x_str          = gga_x_pbe
exc-c_str          = gga_c_pbe
kedf-kedf          = GGA
kedf-k_str         = revAPBEK

[SUB_KS]
calculator         = qe
embed              = KE XC
cell-cut            = 3.5 3.5 3.5
basefile        = qe_in.in
kpoints-grid    = 1 1 1
cell-index         = 0:24
decompose-method   = distance
decompose-radius-O = 0.8
decompose-radius-H = 0.5
kpoints-method = automatic
mix-coef = 0.7


[SUB_KS8]
calculator         = qe
cell-cut            = 3.5 3.5 3.5
embed              = KE XC 
basefile        = qe_in.in
kpoints-grid    = 1 1 1
cell-index         = 24:27
kpoints-method = automatic
mix-coef = 0.7

