#!/bin/bash
#SBATCH --time=5:00:00
#SBATCH --partition=price,main
#SBATCH --job-name=edftpy_test
#SBATCH --nodes=4                  # Number of nodes you require
#SBATCH --ntasks=202                # Total # of tasks across all nodes
#SBATCH --mem=140G                   # Real memory (RAM) required          
#SBATCH --exclusive
#SBATCH --output=slurm.%N.%j.out     # STDOUT output file
#SBATCH --error=slurm.%N.%j.err      # STDERR output file (optional)
#SBATCH --export=ALL                 # Export you current env to the job env
#SBATCH --cluster=amareln

module use /projects/community-old/modulefiles
module load gcc/15.2.0/openssl/3.6.0-krasting
module load intel/19.1.1
module load gcc/14.2.0-cermak libffi/3.3-gc563

PREFIX=/projectsn/mp1009_1/for_all/software_2026/edftpy_2026_2/
source "$PREFIX/bin/activate"

LIBXC_DIR=/projectsn/mp1009_1/for_all/software_2026/libxc

export LD_LIBRARY_PATH=$LIBXC_DIR/lib64:$LD_LIBRARY_PATH
export LIBRARY_PATH=$LIBXC_DIR/lib64:$LIBRARY_PATH
export CPATH=$LIBXC_DIR/include:$CPATH
export PKG_CONFIG_PATH=$LIBXC_DIR/lib64/pkgconfig:$PKG_CONFIG_PATH

export PYTHONPATH=$LIBXC_DIR/pylibxc:$PYTHONPATH
export PYTHONPATH=$LIBXC_DIR/build/lib.linux-x86_64-cpython-310:$PYTHONPATH

NTASKS=$SLURM_NTASKS

mpirun -n $NTASKS python -m edftpy input.ini > log
