[JOB]
task            = Optdensity
calctype        = Force
[PATH]
pp              = ../../../
cell            = ./

[PP]
O               = o_pbe_v1.2.uspp.F.UPF
H               = h_pbe_v1.4.uspp.F.UPF

[OPT]
maxiter         = 200
econv           = 1e-12
olevel          = 2
sdft            = qmmm

[GSYSTEM]
cell-file = xxyz00.xyz 
grid-ecut       = 4860
exc-xc           = pbe
#density-output   = total.xsf

[SUB_KS1]
calculator      = pwscf
embed           = KE XC
kpoints-grid    = 1 1 1
basefile        = qe_in.in
cell-index      = 0:3
opt-update_sleep = 1
cell-cut            = 5 5 5
nprocs = 2
#density-output      =  ks1.xsf


[SUB_MM]
calculator      = mbx
embed           = KE
kpoints-grid    = 1 1 1
basefile        = mbx.json
cell-index      = 3: 
nprocs=1
#density-output      =  mm.xsf

